#%RAML 1.0 DataType
type: object
properties:
    userid:
      required: false 
      type: integer
    username: 
      required: false 
      type: string
    email:  
      required: false 
      type: string
    date_joined: 
      required: false 
      type: string
    modified:  
      required: false 
      type: integer
    type:  
      required: false 
      type: integer
    deleted:
      required: false
      type: boolean




