  [
    {
    "userid": 900,
    "username": "yoni",
    "email": "yoni@gmail.com",
    "date_joined": 1121,
    "modified": 1521,
    "type": 1,
    "deleted": false
    
    },
    {
    "userid": 1000,
    "username": "Dave",
    "email": "dave@gmail.com",
    "date_joined": "1/2/21",
    "modified": 23456,
    "type": 5,
    "deleted": false
    
    },

    {
    "userid": 1001,
    "email": "kal@gmail.com",
    "date_joined": "1321",
    "modified": 1921,
    "type": 7,
    "deleted": false,
    "username": "Kalie"
    },

    {
    "userid": 1002,
    "email": "mer@gmail.com",
    "date_joined": "117/21",
    "modified": 1821,
    "type": 6,
    "deleted": false,
    "username": "Meri"
    },

    {
    "userid": 1003,
    "username": "Selam",
    "email": "sel@gmail.com",
    "date_joined": "1121",
    "modified": 1321,
    "type": 5,
    "deleted": false
    
    },
    {
    "userid": 1004,
    "username": "Meri",
    "email": "mer@yahoo.com",
    "date_joined": "1521",
    "modified": 1721,
    "type": 4,
    "deleted": false
    
    }
  ]