#%RAML 1.0 Library
usage: To define basic liberaries that are used in this resr api raml specification

resourceTypes:
  collection: !include resources/rootResourceType.raml
  
securitySchemes:
  oath: !include auth/securitySchemeOauth.raml

  #basicAuth: !include auth/securityScheme.raml
  #basicAuth: !include auth/securityScheme.raml
# documentation:
#   - !include documentation.raml
types:
  users: !include dataTypes/userType.raml
traits:
  responseMessage: !include traits/responses.raml
  special_trait: !include traits/responses.raml

